- id: conda-export
  name: Conda export environment
  description: This hook keeps the conda environment.yml up to date
  language: script
  entry: conda-export.sh
  always_run: true
  pass_filenames: false
  args: ["--env_pth", "environment.yml", "--", "--from-history"]
